mirrorRepos:
  daocloud: https://release.daocloud.io/chartrepo/daocloud
  daocloud-system: https://release.daocloud.io/chartrepo/daocloud-system
  partner: https://release.daocloud.io/chartrepo/partner
  community: https://release.daocloud.io/chartrepo/community