mirrorRepos:
  addon: https://release.daocloud.io/chartrepo/addon
  system: https://release.daocloud.io/chartrepo/system
  partner: https://release.daocloud.io/chartrepo/partner
  community: https://release.daocloud.io/chartrepo/community