name: Sync

on:
  schedule:
    - cron: "0 19,23,11,15 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyyaml
      - name: Install charts-syncer
        run: |
          curl -LJO https://github.com/yankay/charts-syncer/releases/download/v0.15.0-patched/charts-syncer
          chmod +x charts-syncer
          sudo mv charts-syncer /usr/bin
      - name: Sync
        env:
          TARGET_REPO_AUTH_USERNAME: ${{ secrets.TARGET_REPO_AUTH_USERNAME }}
          TARGET_REPO_AUTH_PASSWORD: ${{ secrets.TARGET_REPO_AUTH_PASSWORD }}
          badge: 'true'
        run: |
          bash ./scripts/sync.sh
      - name: Update badge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BADGE_PREFIX: "git://${{ github.repository }}/gh-pages"
        run: |
          wget https://github.com/wzshiming/putingh/releases/download/v0.6.3/putingh_linux_amd64 -O /usr/local/bin/putingh && chmod +x /usr/local/bin/putingh
          GH_TOKEN="${GH_TOKEN}" putingh "${BADGE_PREFIX}/daocloud-sync-badge.svg" badge.svg
